In [1]:
# Simple analysis of the data used and how the data could be improved for better analysis and marketing.

In [2]:
import pandas as pd
pd.set_option('display.max_row', 100)

In [3]:
train = pd.read_csv('DF914_data.csv', encoding='ISO-8859-1')

/Users/wonhee/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3051: DtypeWarning: Columns (5,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
train.head()

,ClientId,# of Orders Placed,# Different products (SKUs) purchased,# of Items Purchased,Max Orders for one SKU,Total Value of all Orders Placed,City,OriginalState,State,Country,Phone,Real Email,Notes,Opt Out,LastPurchaseDate,FirstPurchaseDate
0,29.0,2.0,1.0,2.0,2.0,27.97,ASPERS,PA,PA,US,NaN,NaN,NaN,NaN,2019-03-15 18:36,2017-06-01 9:44
1,48.0,9.0,1.0,9.0,9.0,123.85,ELIZABETHTOWN,KY,KY,US,NaN,NaN,NaN,NaN,2019-07-18 1:49,2017-06-23 12:57
2,63.0,4.0,1.0,4.0,4.0,57.92,BOCA RATON,FL,FL,US,NaN,NaN,NaN,NaN,2018-06-17 16:16,2017-06-16 6:59
3,125.0,1.0,1.0,1.0,1.0,14.98,San Francisco,California,CA,US,NaN,NaN,NaN,NaN,2018-01-11 17:47,2017-06-27 21:02
4,136.0,1.0,1.0,1.0,1.0,31.99,EDEN,UT,UT,US,NaN,NaN,NaN,NaN,2019-07-16 10:10,2017-06-27 16:31

In [ ]:
# Based on the multiple analysis done previously, there are a couple of improvements that can be made for better use of marketing. 
# ------- 1 -------- 
# First of all, the personal information is all missing and it seems that because the information is private and that some of the buyers might not want
# their personal information to be used some place else, that information was not included and came out as 'Nan' as seen in the above. 
# I believe that the personal information is actually not needed in situations like this as the location and time is more than enough to make analysis for further
# analysis. So I think the data itself does not need to be there and it would definitely reduce time on cleansing the data. 

# ------- 2 --------
# Secondly there were some confusing parts with the last purchase date and first purchase date as it only shows when the buyer has first bought and also bought last
# However, what is confusing about this is that for users who have a long time period between the first and last date, it is almost impossible to make any kind of
# assumption or analysis about how much time they have actually spent on looking at the products before buying. 
# For people who have spent just one minute on purchasing 1 product is enough explanation for me and it can be easily understood. 
# There are also people who have spent alot of time on purchasing between the first and last and it is clear that those people have used this e-commerce to 
# regularly buy products. 
# It would have been better if it showed instead the time in minutes or hours looking at the product online before purchasing with the date rather than
# having the first and last purchases. And to distinguish those who are regular purchasers, to show the total amount of time shown in hours rather than the current
# way of showing. With data like this it would be easier to analyze buyers based on the time spent with how many products and the total cost spent on purchase

# ------- 3 --------
# Thirdly, I couldnt really get the point of original state when we are currently looking at present data with present buyers. The current 'State' already shows
# enough data about all the states except for the few non-state but territorial regions of the US. 

# ------- 4 --------
# Fourth, I wasnt sure about the different between Max orders and # of orders placed. It only shows that a certain buyer has bought more than one item if they have
# and it could be used to analyze the buyers who have bought more than one item but there already exists a column for the # of items purchased with # of orders 
# placed. Instead maybe a better option could be to use 'average number of items bought per order', and then we could use that data to analyze the users
# who have bought more than one item per order. 
 
# ------- 5 -------
# Finally, i think it would be better for analysis if there were information or data about international buyers and not restricted to just customers in the US and her
# regions. It would make it a far more interesting analysis because we could look at the country, location compared to the customers in the US. Furthermore, 
# if there was a column about what type of product the user has bought(e.g. electronic, cosmetics, fashion, etc..) then it would just add more interesting analysis
# which could definitely help with making a better marketing strategy plan. For example, using the time to look at which weekday certain type of products are 
# purchased more along with the location of the buyer could help to create a marketing strategy for that certain product for regular buyers and also to 
# devise plans to get more customers to buying.